name: Create Azure Storage Account

on:
  workflow_dispatch:

jobs:
  create-storage-account:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        run: |
          az cloud set --name AzureCloud
          az login --service-principal -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Create Resource Group
        run: |
          az group create --name ${{ secrets.RESOURCE_GROUP_NAME }} --location ${{ secrets.AZURE_LOCATION }}

      - name: Create Storage Account
        run: |
          az storage account create --name ${{ secrets.STORAGE_ACCOUNT_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --location ${{ secrets.AZURE_LOCATION }} --sku Standard_LRS
